"use client";

import { useActionState } from "react";
import { saveTotpSecret } from "../actions";
import QRCode from "react-qr-code";

const initialState = {
  message: "",
};

export default function Setup({
  secret,
  url,
}: {
  secret: string;
  url: string;
}) {
  const [state, formAction] = useActionState(saveTotpSecret, initialState);

  return (
    <>
      <div className="">
        <div
          className="flex flex-col items-center px-6 py-8 mt-8 
            mx-auto lg:py-0 w-fit"
        >
          <div className="w-full bg-white rounded-lg shadow md:mt-0 sm:max-w-md xl:p-0">
            <div className="p-6 space-y-2 md:space-y-3 sm:p-8">
              <h3 className="text-xl font-semibold pb-4">
                Setup authenticator app
              </h3>

              <p>
                Use you a phone app like Microsoft Authenticator, etc, to scan
                the QR Code, or enter the secret key manually.
              </p>

              <p className="py-2">
                Secret key: <strong>{secret}</strong>
              </p>
              <div
                style={{
                  height: "auto",
                  margin: "0 auto",
                  maxWidth: 150,
                  width: "100%",
                }}
              >
                <QRCode
                  size={256}
                  style={{ height: "auto", maxWidth: "100%", width: "100%" }}
                  value={url}
                  viewBox={`0 0 256 256`}
                />
              </div>

              <div className="pt-4">
                <p className="mb-2">
                  Enter the 6 digits code generated by the authenticator app and
                  click "Continue"
                </p>
              </div>

              <div>
                <p className="mb-3">
                  Verify the code from the authenticator app
                </p>
                <form action={formAction}>
                  <input type="hidden" name="secret" value={secret} />

                  <div>
                    <input
                      type="text"
                      name="code"
                      autoComplete="off"
                      className="bg-gray-50 border border-gray-300 
                        text-gray-900 rounded-lg focus:ring-gray-600 
                        focus:border-gray-600 block p-2"
                      placeholder="XXXXXX"
                    />
                  </div>
                  {state.message && (
                    <div className="py-2 text-red-500 text-sm">
                      {state.message}
                    </div>
                  )}
                  <div className="pt-4">
                    <button
                      type="submit"
                      className="text-white bg-gray-600 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2 text-center"
                    >
                      Continue
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
